version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.0-browsers
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            npm install
            npm run build
            npm run coverage
      - persist_to_workspace:
          root: dist
          paths: wikipedia-previews.production.js
  deploy-gh-pages:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - add_ssh_keys:
          fingerprints:
              - "c3:03:93:79:5d:c7:23:b8:4a:4d:5d:41:e3:38:3f:84"
      - run:
          name: Install dependencies
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@wikimedia.org"
            git config user.name "ci-build"
      - run:
          name: Deploy script to gh-pages
          command: |
            gh-pages --dist dist/wikipedia-previews.production.js
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-gh-pages:
          requires:
            - build
          filters:
            branches:
              only: T240012-ci-demo
