version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.0-browsers
    steps:
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Unit Test (with coverage)
          command: npm run coverage
      - run:
          name: Prepare demo
          command: ./scripts/demo.sh
      - persist_to_workspace:
          root: .
          paths: ./demo
      - run:
          name: Run Chrome test
          command: npm run selenium-chrome
      - run:
          name: Run IE test
          command: npm run selenium-ie
      - run:
          name: Run Edge tests
          command: npm run selenium-edge
      - run:
          name: Run Firefox test
          command: npm run selenium-firefox
      - run:
          name: Run Safari test
          command: npm run selenium-safari
  update-demo:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
              - "c3:03:93:79:5d:c7:23:b8:4a:4d:5d:41:e3:38:3f:84"
      - run:
          name: Prepare
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@wikimedia.org"
            git config user.name "ci-build"
      - run:
          name: Deploy demo
          command: |
            gh-pages --dist demo -m "Update demo [ci skip]"
workflows:
  version: 2
  build:
    jobs:
      - build
      - update-demo:
          requires:
            - build
          filters:
            branches:
              only: master
