version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.0-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Unit Test (with coverage)
          command: npm run coverage
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - run:
          name: Prepare demo
          command: ./scripts/demo.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./demo
            - ./storybook-static
  update-demos:
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Prepare
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@wikimedia.org"
            git config user.name "ci-build"
      - run:
          name: Deploy demo
          command: |
            gh-pages --dist . -m "Update demo [ci skip]"
  test-mainpage:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/testing_mainpage.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test-intra-navigation:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/intra_navigation.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots 
  test-arabic:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/pop-ups/arabic_popup.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test-english:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/pop-ups/english_popup.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test-french:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/pop-ups/french_popup.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test-hindi:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/pop-ups/hindi_popup.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test-indonesia:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/pop-ups/indonesia_popup.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test-spanish:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/pop-ups/spanish_popup.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
  test-thai:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/pop-ups/thai_popup.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
workflows:
  version: 2
  build:
    jobs:
      - build
      - test-mainpage:
          requires:
            - build 
      - test-intra-navigation:
          requires:
            - build
      - test-arabic:
          requires:
            - build 
      - test-english:
          requires:
            - build 
      - test-french:
          requires:
            - build 
      - test-hindi:
          requires:
            - build 
      - test-indonesia:
          requires:
            - build 
      - test-spanish:
          requires:
            - build 
      - test-thai:
          requires:
            - build   
      - update-demos:
          requires:
            - build
          filters:
            branches:
              only: main
          

