version: 2.1
jobs:
  test-mainpage:
    docker:
      - image: 'cypress/base:10'
        environment:
          TERM: xterm
    steps:
      - checkout
      # restore folder with npm dependencies and Cypress binary
      -restore_caches:
        keys:
          - cache-{{ checksum "package.json" }}
      #install npm dependencies and Cypress binary(if first time)
      #if they were cached this is sper quixk
      - run:
          name: Prepare
          command: npm install
      - save_caches:
          keys: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      #starting the server
      - run:
          name: Build
          command: npm run dev
          background: true    
      - run:
          name: Running cypress tests 
          command: node_modules/.bin/cypress run --spec cypress/integration/testing_mainpage.js

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots          
workflows:
  version: 2
  build:
    jobs:
      - build
      - test-mainpage:
          requires:
            - build

